//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CscMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSystemCatalog
    {
        public int ID { get; set; }
        public int CatalogID { get; set; }
        public string CatalogCode { get; set; }
        public string CatalogPrefix { get; set; }
        public string CatalogName { get; set; }
        public int OrderSeq { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Remark { get; set; }
        public byte EditFlag { get; set; }
        public byte DeleteFlag { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyBy { get; set; }
        public string ReferenceCode { get; set; }
    }
}
